version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn main.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - .env.dev
    networks:
      - network_t
    restart: unless-stopped



  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 4444:80
    depends_on:
      - web
    networks:
      - network_t
    restart: unless-stopped


volumes:
  static_volume:
  media_volume:

networks:
  network_t: