# Generated by Django 4.2 on 2023-04-16 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeafKeypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('leaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.leaf')),
            ],
        ),
    ]
