# Generated by Django 4.2 on 2023-04-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_leafkeypoint'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usercourses',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='unique_user_course'),
        ),
    ]
