# Generated by Django 4.2 on 2023-04-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_usercourses_unique_user_course'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userleaf',
            constraint=models.UniqueConstraint(fields=('user', 'leafs'), name='unique_user_leaf'),
        ),
    ]
