# Generated by Django 4.2 on 2023-04-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0010_courseslogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaf',
            name='type',
            field=models.CharField(choices=[('THEORY', 'THEORY'), ('PRACTICE', 'PRACTICE'), ('PROJECT', 'PROJECT')], default='THEORY', max_length=10),
        ),
        migrations.AlterField(
            model_name='userleaf',
            name='status',
            field=models.IntegerField(choices=[(5, 'NOT_INTERESTED'), (1, 'INTERESTED'), (2, 'LEARNING'), (3, 'LEARNED'), (4, 'VALIDATED')], default=5),
        ),
    ]
