# Generated by Django 4.2 on 2023-04-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0011_leaf_type_alter_userleaf_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_in_days',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='format',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('blended', 'Blended')], default='online', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('ru', 'Ukrainian'), ('en', 'English')], default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=8, null=True),
        ),
    ]
